# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d68f6c318dea731763aa6d80acf7b77d8a2612884beb77b7a68e77b5c1625b40ad0de074b1728b207c6c5384dca85b301504bc2847904f7298958e857004cf

test:
  secret_key_base: 92921f922a3331900554fc1201488ce57e417b6efe93ed80bacf125cdf71341144d95f27623fafc9d8624d34e0314e4b11c1ccb1555d3b4583efe41976411605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
